package com.example.exception.finallys;

public class Calculation extends MathOperation{

	@Override
	public void div(int a, int b) {
		
		try {
			int c = a/b;
			System.out.println("Division of a and b is : "+c);
		}finally {
			System.out.println("Any no. is not able to divided by zero");
		}
	}
	
	public static void main(String[] args) {
		
		Calculation calculation = new Calculation();
		calculation.add(10, 20);
		calculation.div(12, 2);
		try {
			
		}catch(Exception e) {
			e.printStackTrace();
		}
	}

	

}
