package com.example.exception.finallys;

public class Calculation extends MathOperation{

	@Override
	public void div(int a, int b) {
		
		try {
			int c = a/b;
			System.out.println("Division of a and b is : "+c);
		}catch(Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void main(String[] args) {
		
		

	}

	

}
